### ISSUE TITLE
Incluir um curso de Git básico como pré requisito para o Exercício de OO

### ISSUE THREAD

**Issue by marcelobidoli** [Cappta/developer-academy#3]

**Comment by ewertonr** [comment]
Acho que nesse curso o ideal é não ensinar o trainee através desses clients como SourceTree, GitKraken e etc. Direto vejo a galera que aprendeu assim sofrendo quando precisa fazer alguma tarefa via linha de comando.
Primeiro aprende o básico via linha de comando e depois escolhe o client que mais interessar. O que acha?

**Comment by CesarNobre** [comment]
Com certeza! tela preta neles!

**Comment by marcelobidoli** [comment]
Coloquei esse curso lá https://www.alura.com.br/curso-online-git
